version: '3.9'

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    ports:
      - "80:80"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
  helloworld:
    image: helloworld:1.0
    container_name: helloworld
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
    networks:
      - traefik
networks:
  traefik:
    name: traefik
    driver: bridge

